name: Lines of Code Counter

on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0' # 每周日运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  count-lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install tokei
        run: |
          curl -LSfs https://japaric.github.io/trust/install.sh | \
            sh -s -- --git meraymond/tokei --target x86_64-unknown-linux-musl --to /usr/local/bin
          
      - name: Count lines of code
        run: |
          # 排除规则
          tokei . \
            --exclude="*.json" \
            --include="doge-v3/v3_epk_config.json" \
            --include="doge-v2/v2_epk_config.json" \
            --exclude="doge-v4/rrpl/rrpl/*" \
            --exclude="LICENSE" \
            --exclude="*.dll"\
            --exclude="*.jar"\
            --exclude="*.ttf"
            --exclude="CONTRIBUTING.md" \
            --exclude="CODE_OF_CONDUCT.md" \
            --exclude="*.lock" \
            --output json > loc.json
          
          # 提取总行数
          TOTAL=$(jq '.Total.code' loc.json)
          echo "Total lines of code: $TOTAL"
          echo "total=$TOTAL" >> $GITHUB_OUTPUT
          
      - name: Generate badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: cfe9e833b1bc0f0df06c258b91feeb2c # 需要替换为 Gist ID
          filename: loc.json
          label: Lines of Code
          message: ${{ steps.count-lines.outputs.total }}
          color: blue
          namedLogo: github